version: "3.8"

services:
  bot:
    image: 421p/cybernapev:latest
    container_name: napevbot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TOD_STORAGE=sqlite
      - TZ=UTC
    volumes:
      - ./data:/app/data
    restart: unless-stopped
